use_frameworks!

target 'ASAttributedLabel_Example' do
  pod 'ASAttributedLabel', :path => '../'

  target 'ASAttributedLabel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
